[2022-01-25 06:35:59,446] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: this_is_first_dag.first_task scheduled__2022-01-14T00:00:00+00:00 [queued]>
[2022-01-25 06:35:59,456] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: this_is_first_dag.first_task scheduled__2022-01-14T00:00:00+00:00 [queued]>
[2022-01-25 06:35:59,456] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-01-25 06:35:59,456] {taskinstance.py:1239} INFO - Starting attempt 1 of 6
[2022-01-25 06:35:59,457] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-01-25 06:35:59,470] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): first_task> on 2022-01-14 00:00:00+00:00
[2022-01-25 06:35:59,475] {standard_task_runner.py:52} INFO - Started process 3878 to run task
[2022-01-25 06:35:59,484] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'this_is_first_dag', 'first_task', 'scheduled__2022-01-14T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmp0fiatw2v', '--error-file', '/tmp/tmpwnwdhylp']
[2022-01-25 06:35:59,488] {standard_task_runner.py:77} INFO - Job 3: Subtask first_task
[2022-01-25 06:35:59,554] {logging_mixin.py:109} INFO - Running <TaskInstance: this_is_first_dag.first_task scheduled__2022-01-14T00:00:00+00:00 [running]> on host ceab856ace11
[2022-01-25 06:35:59,717] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflaw_test
AIRFLOW_CTX_DAG_ID=this_is_first_dag
AIRFLOW_CTX_TASK_ID=first_task
AIRFLOW_CTX_EXECUTION_DATE=2022-01-14T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-14T00:00:00+00:00
[2022-01-25 06:35:59,718] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-01-25 06:35:59,718] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo Hello, this is my first dag. Are you OK?']
[2022-01-25 06:35:59,731] {subprocess.py:85} INFO - Output:
[2022-01-25 06:35:59,732] {subprocess.py:89} INFO - Hello, this is my first dag. Are you OK?
[2022-01-25 06:35:59,732] {subprocess.py:93} INFO - Command exited with return code 0
[2022-01-25 06:35:59,772] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=this_is_first_dag, task_id=first_task, execution_date=20220114T000000, start_date=20220125T063559, end_date=20220125T063559
[2022-01-25 06:35:59,813] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-01-25 06:35:59,854] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-01-25 07:27:42,722] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: this_is_first_dag.first_task scheduled__2022-01-14T00:00:00+00:00 [queued]>
[2022-01-25 07:27:42,733] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: this_is_first_dag.first_task scheduled__2022-01-14T00:00:00+00:00 [queued]>
[2022-01-25 07:27:42,733] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-01-25 07:27:42,733] {taskinstance.py:1239} INFO - Starting attempt 1 of 6
[2022-01-25 07:27:42,733] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-01-25 07:27:42,744] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): first_task> on 2022-01-14 00:00:00+00:00
[2022-01-25 07:27:42,749] {standard_task_runner.py:52} INFO - Started process 336 to run task
[2022-01-25 07:27:42,753] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'this_is_first_dag', 'first_task', 'scheduled__2022-01-14T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpwf48u7y2', '--error-file', '/tmp/tmpzekgamka']
[2022-01-25 07:27:42,757] {standard_task_runner.py:77} INFO - Job 3: Subtask first_task
[2022-01-25 07:27:42,818] {logging_mixin.py:109} INFO - Running <TaskInstance: this_is_first_dag.first_task scheduled__2022-01-14T00:00:00+00:00 [running]> on host 943a4c094194
[2022-01-25 07:27:43,000] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflaw_test
AIRFLOW_CTX_DAG_ID=this_is_first_dag
AIRFLOW_CTX_TASK_ID=first_task
AIRFLOW_CTX_EXECUTION_DATE=2022-01-14T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-14T00:00:00+00:00
[2022-01-25 07:27:43,001] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-01-25 07:27:43,002] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo Hello, this is my first dag. Are you OK?']
[2022-01-25 07:27:43,014] {subprocess.py:85} INFO - Output:
[2022-01-25 07:27:43,014] {subprocess.py:89} INFO - Hello, this is my first dag. Are you OK?
[2022-01-25 07:27:43,014] {subprocess.py:93} INFO - Command exited with return code 0
[2022-01-25 07:27:43,081] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=this_is_first_dag, task_id=first_task, execution_date=20220114T000000, start_date=20220125T072742, end_date=20220125T072743
[2022-01-25 07:27:43,126] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-01-25 07:27:43,209] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
