[2022-01-25 06:36:02,464] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: this_is_first_dag.first_task scheduled__2022-01-21T00:00:00+00:00 [queued]>
[2022-01-25 06:36:02,475] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: this_is_first_dag.first_task scheduled__2022-01-21T00:00:00+00:00 [queued]>
[2022-01-25 06:36:02,475] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-01-25 06:36:02,475] {taskinstance.py:1239} INFO - Starting attempt 1 of 6
[2022-01-25 06:36:02,475] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-01-25 06:36:02,487] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): first_task> on 2022-01-21 00:00:00+00:00
[2022-01-25 06:36:02,492] {standard_task_runner.py:52} INFO - Started process 3901 to run task
[2022-01-25 06:36:02,496] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'this_is_first_dag', 'first_task', 'scheduled__2022-01-21T00:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpu8eruigl', '--error-file', '/tmp/tmp4nwwdcz6']
[2022-01-25 06:36:02,500] {standard_task_runner.py:77} INFO - Job 11: Subtask first_task
[2022-01-25 06:36:02,564] {logging_mixin.py:109} INFO - Running <TaskInstance: this_is_first_dag.first_task scheduled__2022-01-21T00:00:00+00:00 [running]> on host ceab856ace11
[2022-01-25 06:36:02,732] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflaw_test
AIRFLOW_CTX_DAG_ID=this_is_first_dag
AIRFLOW_CTX_TASK_ID=first_task
AIRFLOW_CTX_EXECUTION_DATE=2022-01-21T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-21T00:00:00+00:00
[2022-01-25 06:36:02,733] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-01-25 06:36:02,734] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo Hello, this is my first dag. Are you OK?']
[2022-01-25 06:36:02,742] {subprocess.py:85} INFO - Output:
[2022-01-25 06:36:02,744] {subprocess.py:89} INFO - Hello, this is my first dag. Are you OK?
[2022-01-25 06:36:02,745] {subprocess.py:93} INFO - Command exited with return code 0
[2022-01-25 06:36:02,771] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=this_is_first_dag, task_id=first_task, execution_date=20220121T000000, start_date=20220125T063602, end_date=20220125T063602
[2022-01-25 06:36:02,828] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-01-25 06:36:02,858] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-01-25 07:27:45,591] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: this_is_first_dag.first_task scheduled__2022-01-21T00:00:00+00:00 [queued]>
[2022-01-25 07:27:45,602] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: this_is_first_dag.first_task scheduled__2022-01-21T00:00:00+00:00 [queued]>
[2022-01-25 07:27:45,602] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-01-25 07:27:45,602] {taskinstance.py:1239} INFO - Starting attempt 1 of 6
[2022-01-25 07:27:45,603] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-01-25 07:27:45,614] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): first_task> on 2022-01-21 00:00:00+00:00
[2022-01-25 07:27:45,619] {standard_task_runner.py:52} INFO - Started process 362 to run task
[2022-01-25 07:27:45,623] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'this_is_first_dag', 'first_task', 'scheduled__2022-01-21T00:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpf9i5kheh', '--error-file', '/tmp/tmpwx47cdv5']
[2022-01-25 07:27:45,627] {standard_task_runner.py:77} INFO - Job 11: Subtask first_task
[2022-01-25 07:27:45,824] {logging_mixin.py:109} INFO - Running <TaskInstance: this_is_first_dag.first_task scheduled__2022-01-21T00:00:00+00:00 [running]> on host 943a4c094194
[2022-01-25 07:27:45,880] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflaw_test
AIRFLOW_CTX_DAG_ID=this_is_first_dag
AIRFLOW_CTX_TASK_ID=first_task
AIRFLOW_CTX_EXECUTION_DATE=2022-01-21T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-21T00:00:00+00:00
[2022-01-25 07:27:45,880] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-01-25 07:27:45,881] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo Hello, this is my first dag. Are you OK?']
[2022-01-25 07:27:45,889] {subprocess.py:85} INFO - Output:
[2022-01-25 07:27:45,891] {subprocess.py:89} INFO - Hello, this is my first dag. Are you OK?
[2022-01-25 07:27:45,891] {subprocess.py:93} INFO - Command exited with return code 0
[2022-01-25 07:27:45,919] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=this_is_first_dag, task_id=first_task, execution_date=20220121T000000, start_date=20220125T072745, end_date=20220125T072745
[2022-01-25 07:27:45,956] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-01-25 07:27:45,985] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
