[2022-01-25 06:35:59,465] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: this_is_first_dag.first_task scheduled__2022-01-12T00:00:00+00:00 [queued]>
[2022-01-25 06:35:59,474] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: this_is_first_dag.first_task scheduled__2022-01-12T00:00:00+00:00 [queued]>
[2022-01-25 06:35:59,474] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-01-25 06:35:59,474] {taskinstance.py:1239} INFO - Starting attempt 1 of 6
[2022-01-25 06:35:59,475] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-01-25 06:35:59,486] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): first_task> on 2022-01-12 00:00:00+00:00
[2022-01-25 06:35:59,490] {standard_task_runner.py:52} INFO - Started process 3879 to run task
[2022-01-25 06:35:59,498] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'this_is_first_dag', 'first_task', 'scheduled__2022-01-12T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpozrvvphj', '--error-file', '/tmp/tmp5kqbx_xf']
[2022-01-25 06:35:59,502] {standard_task_runner.py:77} INFO - Job 4: Subtask first_task
[2022-01-25 06:35:59,562] {logging_mixin.py:109} INFO - Running <TaskInstance: this_is_first_dag.first_task scheduled__2022-01-12T00:00:00+00:00 [running]> on host ceab856ace11
[2022-01-25 06:35:59,631] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflaw_test
AIRFLOW_CTX_DAG_ID=this_is_first_dag
AIRFLOW_CTX_TASK_ID=first_task
AIRFLOW_CTX_EXECUTION_DATE=2022-01-12T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-12T00:00:00+00:00
[2022-01-25 06:35:59,632] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-01-25 06:35:59,633] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo Hello, this is my first dag. Are you OK?']
[2022-01-25 06:35:59,644] {subprocess.py:85} INFO - Output:
[2022-01-25 06:35:59,649] {subprocess.py:89} INFO - Hello, this is my first dag. Are you OK?
[2022-01-25 06:35:59,650] {subprocess.py:93} INFO - Command exited with return code 0
[2022-01-25 06:35:59,702] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=this_is_first_dag, task_id=first_task, execution_date=20220112T000000, start_date=20220125T063559, end_date=20220125T063559
[2022-01-25 06:35:59,749] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-01-25 06:35:59,864] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-01-25 07:27:42,744] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: this_is_first_dag.first_task scheduled__2022-01-12T00:00:00+00:00 [queued]>
[2022-01-25 07:27:42,756] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: this_is_first_dag.first_task scheduled__2022-01-12T00:00:00+00:00 [queued]>
[2022-01-25 07:27:42,756] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-01-25 07:27:42,756] {taskinstance.py:1239} INFO - Starting attempt 1 of 6
[2022-01-25 07:27:42,756] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-01-25 07:27:42,768] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): first_task> on 2022-01-12 00:00:00+00:00
[2022-01-25 07:27:42,772] {standard_task_runner.py:52} INFO - Started process 337 to run task
[2022-01-25 07:27:42,781] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'this_is_first_dag', 'first_task', 'scheduled__2022-01-12T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpymm4ros2', '--error-file', '/tmp/tmpdf4z6pi1']
[2022-01-25 07:27:42,785] {standard_task_runner.py:77} INFO - Job 4: Subtask first_task
[2022-01-25 07:27:42,843] {logging_mixin.py:109} INFO - Running <TaskInstance: this_is_first_dag.first_task scheduled__2022-01-12T00:00:00+00:00 [running]> on host 943a4c094194
[2022-01-25 07:27:42,905] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflaw_test
AIRFLOW_CTX_DAG_ID=this_is_first_dag
AIRFLOW_CTX_TASK_ID=first_task
AIRFLOW_CTX_EXECUTION_DATE=2022-01-12T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-12T00:00:00+00:00
[2022-01-25 07:27:42,906] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-01-25 07:27:42,906] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo Hello, this is my first dag. Are you OK?']
[2022-01-25 07:27:42,916] {subprocess.py:85} INFO - Output:
[2022-01-25 07:27:42,917] {subprocess.py:89} INFO - Hello, this is my first dag. Are you OK?
[2022-01-25 07:27:42,917] {subprocess.py:93} INFO - Command exited with return code 0
[2022-01-25 07:27:42,958] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=this_is_first_dag, task_id=first_task, execution_date=20220112T000000, start_date=20220125T072742, end_date=20220125T072742
[2022-01-25 07:27:42,989] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-01-25 07:27:43,028] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
